[package]
name = "magpie_csnf"
version.workspace = true
edition.workspace = true

[dependencies]
magpie_ast = { path = "../magpie_ast" }
magpie_diag = { path = "../magpie_diag" }
blake3 = { workspace = true }
