[package]
name = "magpie_own"
version.workspace = true
edition.workspace = true

[dependencies]
magpie_hir = { path = "../magpie_hir" }
magpie_types = { path = "../magpie_types" }
magpie_diag = { path = "../magpie_diag" }
